[project]
name = "ai-agent-observability-phoenix"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "arize-phoenix>=19.15.0",
    "arize-phoenix-evals>=3.3.0",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "litellm>=1.95.0",
    "llama-index>=0.14.23",
    "llama-index-embeddings-ollama>=0.9.0",
    "llama-index-embeddings-openai>=0.6.0",
    "llama-index-llms-ollama>=0.10.1",
    "llama-index-llms-openai>=0.7.10",
    "llama-index-readers-confluence>=0.7.0",
    "openinference-instrumentation-llama-index>=4.4.4",
    "python-dotenv>=1.2.2",
]
